name: build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        id: version
        uses: paulhatch/semantic-version@v5.4.0

      - name: Create GitHub tag and release
        uses: softprops/action-gh-release@v2.0.5
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          generate_release_notes: true
